### ISSUE TITLE
Scopus400Error: Invalid Input (cursor)

### ISSUE THREAD

**Issue by raffaem** [pybliometrics-dev/pybliometrics#160] opened 2020-09-17 10:05 UTC
I'm trying to run the following query:

` AU-ID(57202862024)`

The query works in Scopus's [Advanced search](https://www.scopus.com/search/form.uri?display=advanced&zone=header&origin=resultslist).

But by trying it in pybliometrics, I get a Scopus400Error. 

Here is my script:

```
from pybliometrics.scopus import ScopusSearch

query = f"AU-ID(57202862024)"
print(f"Query: {query}")

# Run Scopus search
res = ScopusSearch(query, subscriber=True, download=True, verbose=True) 
print(res.results)  
```

Here is the output:

```
ions>python test.py
Query: AU-ID(57202862024)
Downloading results for query "AU-ID(57202862024)":
Traceback (most recent call last):██-------------------------| 50.00% Complete
  File "test.py", line 7, in <module>
    res = ScopusSearch(query, subscriber=True, download=True, verbose=True)
  File "C:\Users\Raffaele\anaconda3\lib\site-packages\pybliometrics\scopus\scopus_search.py", line 198, in __init__
    Search.__init__(self, query=query, api='ScopusSearch', refresh=refresh,
  File "C:\Users\Raffaele\anaconda3\lib\site-packages\pybliometrics\scopus\superclasses\search.py", line 76, in __init__
    Base.__init__(self, qfile, refresh, params=params, url=SEARCH_URL[api],
  File "C:\Users\Raffaele\anaconda3\lib\site-packages\pybliometrics\scopus\superclasses\base.py", line 90, in __init__
    data, header = _parse(res, n, url, params, verbose,
  File "C:\Users\Raffaele\anaconda3\lib\site-packages\pybliometrics\scopus\superclasses\base.py", line 176, in _parse
    resp = get_content(url, params, *args, **kwds)
  File "C:\Users\Raffaele\anaconda3\lib\site-packages\pybliometrics\scopus\utils\get_content.py", line 86, in get_content
    raise errors[resp.status_code](reason)
pybliometrics.scopus.exception.Scopus400Error: Invalid Input (cursor)
```

**Comment by AndreaUnige** [comment] 2020-09-17 15:34
Hi,
I get a similar situation with the `get_documents()` function. It is really really strange.
If I do:
`singleAuth = AuthorRetrieval(54968905900);`
I can correctly retrieve author's detail (name and number of products) by doing `print(singleAuth)`
Furthermore, if I do `singleAuth.get_documents()` I can correctly retrieve author's documents. This is fine.

If I repeat the **same commands** with another ScopusID like 22937828700 I I can correctly retrieve author's detail (name and number of products) by doing `print(singleAuth)` but I cannot get author's documents.

In particular, by doing `singleAuth.get_documents()` this is what I got:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrea/.local/lib/python3.7/site-packages/pybliometrics/scopus/author_retrieval.py", line 309, in get_documents
    s = ScopusSearch(f'AU-ID({self.identifier})', **kwds)
  File "/home/andrea/.local/lib/python3.7/site-packages/pybliometrics/scopus/scopus_search.py", line 200, in __init__
    download=download, verbose=verbose, **kwds)
  File "/home/andrea/.local/lib/python3.7/site-packages/pybliometrics/scopus/superclasses/search.py", line 77, in __init__
    download=download, max_entries=max_entries, verbose=verbose)
  File "/home/andrea/.local/lib/python3.7/site-packages/pybliometrics/scopus/superclasses/base.py", line 91, in __init__
    *args, **kwds)
  File "/home/andrea/.local/lib/python3.7/site-packages/pybliometrics/scopus/superclasses/base.py", line 176, in _parse
    resp = get_content(url, params, *args, **kwds)
  File "/home/andrea/.local/lib/python3.7/site-packages/pybliometrics/scopus/utils/get_content.py", line 86, in get_content
    raise errors[resp.status_code](reason)
pybliometrics.scopus.exception.Scopus400Error: Invalid Input (cursor)


It seems to me that the `AuthorRetrieval` only works in some cases but I still haven't figured out which are the good ones and which are the bad ones.

Did someone expect a similar behavior ?

**Comment by JAyalaU** [comment] 2020-09-17 20:21
Having the exact same issue with this query:

```
s = ScopusSearch("AF-ID(60012708) AND PUBYEAR > 2014 AND PUBYEAR < 2016",subscriber=True, view='COMPLETE', download=True)
```

But my query with another ID worked yesterday before midnight, and today no ID seems to work.

**Comment by Michael-E-Rose** [comment] 2020-09-17 21:31
The error is that the Scopus API doesn't accept the next cursor pointer for pagination. But it's not the case for all queries: `'SOURCE-ID(17557) AND PUBYEAR IS 2000'` works. Need to inquire with the Scopus developers whether something happend on their end before I come up with fixtures.

**Comment by AndreaUnige** [comment] 2020-09-18 06:48
Dear @Michael-E-Rose ,
it is really good to see that you are really committed to solve any raised issue.
This is a good job.

Thank you!

**Comment by Michael-E-Rose** [comment] 2020-09-18 06:57
It's an unknown bug on their end, a Scopus developer confirmed. They're working on it with highest priority.

The reason is simply that some next pointers (i.e. links) are not well encoded: If there's a percentage sign or a plus sign or something, one gets the error that you guys found. This likely happend following a some change they undertook.

**Comment by AndreaUnige** [comment] 2020-09-18 07:00
Got it.
How can be aware of the fact that they have fixed the issue ?

**Comment by Michael-E-Rose** [comment] 2020-09-18 07:08
I guess either when the queries work again, or when I close the issue based on my Scopus contact's confirmation that the bug has been solved.

**Comment by Michael-E-Rose** [comment] 2020-09-21 16:26
It's working again! But you guys probably found this out before me. Thanks for founding and reporting this!

**Closed by Michael-E-Rose** 2020-09-21 16:26 UTC
Labels: Backend
